In [1]:
def matriz_3x3(matriz: list):
    import numpy as np
    if len(matriz) == 3:
        matriz = np.array(matriz)
        print(matriz)
        return matriz.diagonal(offset=0).sum()

In [2]:
matriz_3x3([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


15