In [68]:
def matriz_4x4(matriz: list):
    import numpy as np
    matriz = np.array(matriz)
    print(matriz, end="\n\n")
    return len([n for l in matriz for n in l if n > 10])

In [15]:
valores = [int(input(f"Informe o {i + 1}º valor: ")) for i in range(16)]

In [26]:
valores = [valores[:4], valores[4:8], valores[8:12], valores[12:]]

In [69]:
print(f"Quantidade de números que são maiores que 10: {matriz_4x4(valores)}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Quantidade de números que são maiores que 10: 5
