In [17]:
def matriz_3x3(matriz: list):
    import numpy as np
    if len(matriz) == 3:
        matriz = np.array(matriz)
        print(matriz)
        diagonal_secundaria = list(matriz.diagonal(offset=-2))
        diagonal_secundaria.append(matriz.diagonal(offset=0)[1])
        diagonal_secundaria.append(matriz.diagonal(offset=2)[0])
        return sum(diagonal_secundaria)

In [18]:
matriz_3x3([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


15